services:
  - type: web
    name: uchat-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: .
    plan: starter
    region: oregon
    healthCheckPath: /
    dockerBuildArgs:
      API_URL: https://uchat-backend.onrender.com/
    envVars:
      - key: API_BIND
        value: 0.0.0.0:8070
      - key: API_DATABASE_URL
        sync: false
      - key: API_PRIVATE_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://uchat.pages.dev
