[build]
target = "frontend/index.html"
dist = "dist"
release = true

[[hooks]]
stage = "build"
command = "sh"
command_arguments = [
    "-c",
    "npx @tailwindcss/cli -i frontend/src/tailwind.css -o $TRUNK_STAGING_DIR/tailwind.css -m",
]
